First commit
fomin-petr/Sprint_6 pull request #1
Opened 2023-11-15 20:51 UTC by fomin-petr

2023-11-19 18:14 UTC, kadirovgm requested changes

2023-11-19 18:14 UTC, kadirovgm commented on pages/about_rent_page.py
> +
Нужно исправить: ты не применяешь консепцию POM и базового класса BasePage

создай пожалуйста файл base_page.py и создай там базовый класс

класс BasePage - это такой родительский класс, в котором содержатся общие методы, такие как: клик по определенному элементу, скролл к определенному элементу, ожидание определенного элемента, изменение табов итд.

То есть эти методы не привязаны к определенной странице, и могут быть переиспользованы в любой POM-странице, стоит туда добавить именно такие методы.

BasePage не могут быть свои локаторы, ведь предполагается, что для методов BasePage подходят локаторы POM-страницы

2023-11-19 18:14 UTC, kadirovgm commented on pages/about_rent_page.py
> +    def __init__(self, driver):
нужно исправить: такой конструктор стоит добавить в BasePagе, а в других POM классах страниц наследовать BasePage, тем самым наследуя и init

2023-11-19 18:14 UTC, kadirovgm commented on pages/about_rent_page.py
> +class AboutRent:
Нужно исправить: Если придерживаться классических рекомендации POM, то тебе нужно наследоваться в этом классе от BasePage - как раз таки для того, чтобы наследовать его общие методы.

2023-11-19 18:14 UTC, kadirovgm commented on pages/about_rent_page.py
> +    def fill_out_form(self, when_date, term, color, comment):
отлично! молодец, что объединил маленькие методы для заполнения полей в один fill_form, так как в тестах мы должны указывать именно высокоуровневые шаги, типа заполнить все данные на странице

2023-11-19 18:14 UTC, kadirovgm commented on pages/order_first_page.py
> +class OrderFirstPage:
нужно исправить: наследовать базовый класс

2023-11-19 18:14 UTC, kadirovgm commented on pages/order_first_page.py
> +    def __init__(self, driver):
нужно исправить: должен быть в базовом классе

2023-11-19 18:14 UTC, kadirovgm commented on tests/test_important_questions.py
> +    reply_order = [[0, 'Сутки — 400 рублей. Оплата курьеру — наличными или картой.'],
нужно исправить: тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-11-19 18:14 UTC, kadirovgm commented on tests/test_important_questions.py
> +        assert important_reply == expected_reply
хороший тест! советую еще в assert-ы добавить assert messages, чтобы более подробно описывать ошики

2023-11-19 18:14 UTC, kadirovgm commented on tests/test_order_positive_flow.py
> +        assert page.driver.current_url == 'https://qa-scooter.praktikum-services.ru/'
нужно исправить: мы пишем атомарные тесты ввиду их положительных особенностей, что означает, что в одном тест должна быть ровно одна функциональная проверка, а тут несколько тестов перемешено в один тестовый метод, советую разделить

2023-11-19 18:14 UTC, kadirovgm commented on tests/test_order_positive_flow.py
> +        assert page.driver.current_url == 'https://qa-scooter.praktikum-services.ru/'
можно лучше: проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-11-19 18:14 UTC, kadirovgm commented on tests/test_order_positive_flow.py
> +                (By.XPATH, '//form[ @action = "https://yandex.ru/search/"]')))
нужно исправить: все локаторы должны находиться в одном месте, в тесте локаторы могут только вызываться, не нужно их тут прописывать, иначе при увеличении количества тестов будет очень трудно их поддерживать

2023-11-20 20:18 UTC, fomin-petr commented on pages/about_rent_page.py
> +
исправил

2023-11-20 20:18 UTC, fomin-petr commented on pages/about_rent_page.py
> +    def __init__(self, driver):
исправил

2023-11-20 20:18 UTC, fomin-petr commented on pages/about_rent_page.py
> +class AboutRent:
исправил

2023-11-20 20:18 UTC, fomin-petr commented on pages/order_first_page.py
> +class OrderFirstPage:
исправил

2023-11-20 20:18 UTC, fomin-petr commented on pages/order_first_page.py
> +    def __init__(self, driver):
исправил

2023-11-20 20:19 UTC, fomin-petr commented on tests/test_order_positive_flow.py
> +                (By.XPATH, '//form[ @action = "https://yandex.ru/search/"]')))
исправил

2023-11-20 20:25 UTC, fomin-petr commented on tests/test_important_questions.py
> +    reply_order = [[0, 'Сутки — 400 рублей. Оплата курьеру — наличными или картой.'],
исправил

2023-11-20 21:03 UTC, fomin-petr commented on tests/test_order_positive_flow.py
> +        assert page.driver.current_url == 'https://qa-scooter.praktikum-services.ru/'
разбил проверки, задание кривое

2023-11-21 14:55 UTC, kadirovgm requested changes

2023-11-21 14:55 UTC, kadirovgm commented on pages/base_page.py
> +
супер!

2023-11-21 14:55 UTC, kadirovgm commented on pages/about_rent_page.py
> +class AboutRent(BasePage):
отлично, молодец!

2023-11-21 14:55 UTC, kadirovgm commented on pages/order_first_page.py
> +    name_field = [By.XPATH, '//input[ @placeholder="* Имя"]']
нужно исправить: почему эти локаторы здесь находятся, если ты их уже вынес в папку locators?

2023-11-21 14:55 UTC, kadirovgm commented on pages/start_page.py
> +    accept_cookies_button = [By.ID, 'rcc-confirm-button']
нужно исправить: почему тут дублируются локаторы, которые были вынесены в папку locators?

2023-11-21 14:55 UTC, kadirovgm commented on tests/data.py
нужно исправить: data.py - это тестовые данные, но не сами тесты, так что в папке tests их держать нелогично

2023-11-21 14:55 UTC, kadirovgm commented on tests/conftest.py
> +
нужно исправить: давай не держать conftest.py. в папке tests, который предполагает только тестовые файлы с тестами

2023-11-21 14:55 UTC, kadirovgm commented on tests/conftest.py
> +    driver.get('https://qa-scooter.praktikum-services.ru/')
можно лучше: Urls также лучше вынести как класс в data.py

2023-11-21 14:55 UTC, kadirovgm commented on tests/test_order_positive_flow.py
> +    def test_scooter_logo_button_after_order(self, scooter_page, name, surname, address, metro, phone, term, color, comment):
а точно этот тест нужно делать именно после создания заказа?

2023-11-21 20:22 UTC, fomin-petr commented on tests/test_order_positive_flow.py
> +    def test_scooter_logo_button_after_order(self, scooter_page, name, surname, address, metro, phone, term, color, comment):
ну такое задание - заказать самокат и нажать на кнопки, поэтому и был один тест, он как часть позитивного сценария

2023-11-21 20:29 UTC, fomin-petr commented on tests/conftest.py
> +    driver.get('https://qa-scooter.praktikum-services.ru/')
вынес в дату в отдельный класс

2023-11-21 20:30 UTC, fomin-petr commented on tests/conftest.py
> +
вынес из папки. в прошлом спринте почему-то фикстуры не работали из корня проекта, только из тестов

2023-11-21 20:30 UTC, fomin-petr commented on tests/data.py
вынес дата в корень проекта

2023-11-21 20:30 UTC, fomin-petr commented on pages/start_page.py
> +    accept_cookies_button = [By.ID, 'rcc-confirm-button']
забыл, убрал

2023-11-21 20:30 UTC, fomin-petr commented on pages/order_first_page.py
> +    name_field = [By.XPATH, '//input[ @placeholder="* Имя"]']
забыл убрать. убрал

2023-11-22 22:31 UTC, kadirovgm approved these changes

2024-01-07 16:25 UTC, merged